### ISSUE TITLE
Limit number of files to be uploaded

### ISSUE THREAD

**Issue by taroongunessee** [promosis/file-upload-with-preview#11]
I need some help please. How can we limit the number of files to be uploaded?  
Thanks

**Comment by johndatserakis** [comment]
Hey there - good question!

Right now, the library does not provide an out of the box solution to do this. But, I've created a [jsfiddle](https://jsfiddle.net/johndatserakis/w78ykvma/7/) for you to demonstrate how to make this work. It's a bit rudimentary, but it gets the job done and should provide you the feature you were looking for. Basically, we make use of the `imageSelected` event hook to let us know when the selecting action has taken place. Then we use the `fileLimit` variable to prune our image thumbnails and `cachedFileArray` accordingly.

Make sure to set the `multiple` option in your HTML on the input, and to pass `true` as the second parameter in the library initialization (to allow multiple thumbnails in the preview pane). Also, a caveat is that we need to use a short `setTimeout` to wait for the image thumbnails to display. This causes a small flash-of-content, but I think will be ok for your needs at the moment.

We are planning a little bit of a rewrite to this library in the coming weeks - mainly to allow an option object to be passed in to the initialization, so we can provide a bit more customization and some cleaner code. Until then, this should hold those over looking to limit file uploads. 

[Here's the jsfiddle](https://jsfiddle.net/johndatserakis/w78ykvma/7/)

Below is the js code in the fiddle:

```javascript
// Initialize
var upload = new FileUploadWithPreview('myFirstImage', true)

// Set file limit
var fileLimit = 3

// Register for the change event on the input
upload.imageSelected = function(event) {
	
  // If we haven't selected more than your limit, let's exit here
  if (upload.cachedFileArray.length < fileLimit) {
    return
  }

  // Splice the real cachedFileArray with your file limit
  upload.cachedFileArray = upload.cachedFileArray.splice(0, fileLimit)

  // Must set a small timeout because the thumbnails take some time to be drawn.
  window.setTimeout(function() {

    // Grab all the image thumbnails
    var imageThumbnails = document.querySelectorAll('.custom-file-container__image-multi-preview')

    // Loop through them, removing them from the dom if they're over the limit
    for (var x = 0; x < imageThumbnails.length; x++) {
      if (x > (fileLimit - 1)) {
        imageThumbnails[x].remove()
      }
    }

    // Make sure to update our input count
    upload.inputLabel.innerHTML = upload.cachedFileArray.length + ' files selected';

    // Here you'll see the cachedFileArray contains the correct number of images
    console.log(upload.cachedFileArray)

  }, 500)
  
};
```

Let us know if that works for you.

**Comment by johndatserakis** [comment]
Closing for now - let us know how it goes!
