### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Batarian711** [promosis/file-upload-with-preview#20]
If there is an idea, I want to design a logo for you. I can volunteer if you want anything. What dou you say?

**Comment by johndatserakis** [comment]
Hey there - thank you for offering to do this! Sorry for the late response. 

Did you have something in mind or a draft of some sort? I don't want you to spend too much time on this as it's not a crazy big project or anything - but I am curious as to what you're thinking.

**Comment by johndatserakis** [comment]
Hello - I'll close this for now - reply here with more info if you like. Thank you!
