### ISSUE TITLE
Uncaught TypeError: FileUploadWithPreview is not a constructor

### ISSUE THREAD

**Issue by rogerarruda** [promosis/file-upload-with-preview#21]
Hello, I'm having the same problem (#19)  importing from NPM into a JS file.

File **plugins.js** using webpack:

`window.FileUploadWithPreview = require('file-upload-with-preview');`

When I see in the browser, the error appears:

**Uncaught TypeError: FileUploadWithPreview is not a constructor**

My script into HTML

```
<script src="js/plugins.js" type="text/javascript"></script>
<script type="application/javascript">
        const upload = new FileUploadWithPreview('uploadImage', { text: {chooseFile: 'Selecione um arquivo', browse: 'Selecionar'} });
</script>
```

**Comment by johndatserakis** [comment]
Hey there - sorry it's giving you trouble.

I believe the issue you're having is related to the version of `file-upload-with-preview` you are using.

In your current installation, you can add `default` to your initialization, like this:

```javascript
const upload = new FileUploadWithPreview.default('uploadImage', { text: {chooseFile: 'Selecione um arquivo', browse: 'Selecionar'} });
```

Or you could update your version to the latest, which is `3.4.3` - which I recommend. Then you should be able to use the code you already have. Just make sure to delete your package-lock.json if you need to force the update in your app.

Let me know if that works for you - thank you.

**Comment by rogerarruda** [comment]
Hello, thank you very much for the help.
I put the pattern and it worked, I'll try to force the upgrade to test.

According to package-lock.json it says "version" is installed: "3.4.3", but I'll try to run again.

Thank you very much.
