### ISSUE TITLE
Feature request: Change  "X files selected" text

### ISSUE THREAD

**Issue by damonbakker** [promosis/file-upload-with-preview#22]
We can already enter our own strings for the browse button and choose files text.

It would be nice if we could also change the text "X files selected".
This way we could localize it for languages other than English.

**Comment by damonbakker** [comment]
Looks like this is tied to line 176 in file-upload-with-preview.js

```
 processFile(file) {
        // Update our input label here based on instance selectedFilesCount
        if (this.selectedFilesCount === 0) {
            this.inputLabel.innerHTML = this.options.text.chooseFile
        } else if (this.selectedFilesCount === 1) {
            this.inputLabel.innerHTML = file.name
        } else {
            this.inputLabel.innerHTML = `${ this.selectedFilesCount } files selected`
        }

**Comment by johndatserakis** [comment]
Hey @damonbakker - good suggestion - in the next coming days we'll be adding this feature. We'll update here when it's added. Thank you.

**Comment by deniseileen** [comment]
Hey @damonbakker, thanks for the suggestion! We've added this to the options object, so you can change the `X files selected` default text by setting `text.selectedCount` as follows: 
```js
var upload = new FileUploadWithPreview('myUniqueUploadId', {
    showDeleteButtonOnImages: true,
    text: {
        selectedCount: 'Custom Files Selected Copy'
    }
})
```
