### ISSUE TITLE
maxCount

### ISSUE THREAD

**Issue by arabi-kabir** [promosis/file-upload-with-preview#26]
maxCount doesn't working to limit the images uploads. Can you give an example how to write the script.? 
![Screenshot from 2019-11-14 18-28-34](https://user-images.githubusercontent.com/30126556/68857255-a5bf4880-070c-11ea-9ccc-0d6ebdee5142.png)

**Comment by johndatserakis** [comment]
Hi there!

Hmm, I see that you're setting the option correctly - have you made sure that your version is updated to the latest release? That'll be version `4.0.8`.

I made a quick [codepen](https://codepen.io/johndatserakis/pen/pooYwJQ?editors=1010) to show that the `maxFileCount` is working correctly on the latest version.

Try that and let me know, thanks!

**Comment by arabi-kabir** [comment]
Thank you so much. It works with the updated version. :)
