### ISSUE TITLE
How to check image dimensions(width and height) before preview  and upload

### ISSUE THREAD

**Issue by codetestmg** [promosis/file-upload-with-preview#27]
Thanks for the library.easy to integrate.

**Comment by johndatserakis** [comment]
Hi there! Thanks for checking out the project.

To check the image dimensions before upload, you could create a function that handles the evaluation and is run each time a file is uploaded.

To run a function each time files are uploaded, you could hook into the `fileUploadWithPreview:imagesAdded` `window.addEventListener` in your code.

To show you an example of how to get the width and height of the images that have been uploaded, I have set up a [small example](https://codepen.io/johndatserakis/pen/jOEWGYw?editors=1111), but in this case, some code is run each time the **Print Image's Width And Height To Console** is clicked in the bottom left. Click the button after you have added a few images and then open your console. You'll see the images widths and heights displayed there. You can check out the code in the JavaScript section of the codepen to see how I inspected the image array.

This should get you going in the right direction. Let me know if I can help further, thank you.

**Comment by johndatserakis** [comment]
Let me know if this ends up working for you - closing for now.
