### ISSUE TITLE
Not able to get the image on server.

### ISSUE THREAD

**Issue by insaurabh** [promosis/file-upload-with-preview#28]
My html

```html
<input type="hidden" name="upload_log" id="upload-log" value="" />
   <div class="upload-log-images">
   <div class="custom-file-container" data-upload-id="upload-log-images">
     <label>Upload File <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">&times</a></label>
     <label class="custom-file-container__custom-file" >
         <input type="file" class="custom-file-container__custom-file__custom-file-input" accept=".png, .jpg, .jpeg" multiple>
        <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />
       <span class="custom-file-container__custom-file__custom-file-control"></span>
      </label>
      <div class="custom-file-container__image-preview"></div>
        </div>
  </div>
```

What i understood is i have all the valid images in `cachedFileArray`.

I am trying to sending complete array in hidden input. 

```js
window.addEventListener('fileUploadWithPreview:imageDeleted', function(e) {
    if (e.detail.uploadId === 'upload-log-images') {
        jQuery('#upload-log').val(JSON.stringify(e.detail.cachedFileArray))
    }
})
```

At the server level.
```php
 $files =   $upload_log = json_decode(utf8_encode(stripslashes($_POST['upload_log'])), true);
```

output is 
```php

Array
(
    [0] => Array
        (
            [token] => pvf6dfs1p65k520olz9r
        )

    [1] => Array
        (
            [token] => 3tii69591shepm5x6apzys
        )

)
```

**Comment by johndatserakis** [comment]
Hello there,

I see that you're having issues uploading the files found in the `cachedFileArray` to your PHP backend.

In looking at your code, I see a few places that could be causing the issue.

First, I understand that you want to pass the `cachedFileArray`, which is an `array` of JavaScript `Files` using a hidden input. To be honest, I don't think this will work. I'm not totally sure, but to me, especially with the way you are `JSON.stringify()`'ing the data, that will not pass the `Files` to the backend properly.

Next, to access these files, once they are uploaded correctly from the frontend, the files will usually be in the `$_FILES` variable in the PHP world. Now, this is all dependent on how you have your environment up, so this may not be the case for you, but this is the standard case.

So, if it were me, I would try to upload the files in a [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) type of object, which then you would send to the backend and would appear in the `$_FILES` variable on the PHP side.

Here's some reading on this: 
[How to pass file from JavaScript to PHP?](https://stackoverflow.com/a/33971275/8014660)
[jQuery AJAX file upload PHP](https://stackoverflow.com/a/23981045/8014660)
[How to upload Multiple Image files with jQuery AJAX and PHP](https://makitweb.com/how-to-upload-multiple-image-files-with-jquery-ajax-and-php/)

Let me know, thank you.

**Comment by insaurabh** [comment]
I wrote a small library as per the requirement, that works fine and cross browser compatible as well.

I am may be wrong but even if I  JSON.stringify() and parse back to arrays the `cachedFileArray` in console itself not giving the proper output.

I checked all the previous bugs but one have that issue.

Still if you check it once. 

And yes formData is a  good option but  I have to do just image preview work and complete project is already in production. To use formData I have to change many things in form submission and that will be a risky part :cry:

**Comment by johndatserakis** [comment]
Hmm, honestly I'm not sure, as I think it's the actual act of running `JSON.stringify()` that changes the type of data the `cachedFileArray` is holding and therefore causing the issue, which would be impossible to solve at that point.

I just responded to someone here about the `FormData` method - I know you said that won't work for you know, but let me share that code here, so that maybe it can give you some idea on where you could go from here. Below is the copied code: 

---

```javascript
var formElement = document.getElementById('entry-form');
var formData = new FormData(formElement);
formData.append('firstImage', upload.cachedFileArray[0]); // This will get the first image

$.ajax({
  url: "entry.php",
  type: "POST",
  dataType: "json",
  async: true,
  data: formData,
  contentType: false,
  processData: false,
  cache: false,
  success: function(data) {
    console.log(data)
  },
  error: function(error) {
    console.log(error)
  },
  complete: function(data) {
    console.log(data)
  }
})
```

Of course, if you have multiple images, you'll want to loop over them and add them accordingly to your formData object.

Ok, so if you follow this pattern, and have your backend PHP set up correctly, you'll be able to access these files in the `$_FILES` variable in the PHP - and more specifically, the `$_FILES['firstImage']` variable according to this example.

---

Sorry I can't be of more help. Thank you.

**Comment by johndatserakis** [comment]
Closing for now
