### ISSUE TITLE
Id

### ISSUE THREAD

**Issue by cjustinobi** [promosis/file-upload-with-preview#3]
I'm trying to upload file, but I got the error below.
I am accessing the id with:

    <div class="custom-file-container" data-upload-id="myPdf">
                <label>Upload File <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">x</a></label>
                <label class="custom-file-container__custom-file" >
                    <input type="file" @change="addPdf()" class="custom-file-container__custom-file__custom-file-input" accept="*">
                    <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />
                    <span class="custom-file-container__custom-file__custom-file-control"></span>
                </label>
                <div class="custom-file-container__image-preview"></div>
            </div>

in the script section of my vue:

    saveBook() {
              let p = document.getElementById('myPdf')
              let upload = new FileUploadWithPreview(p);
              console.log(upload);
}
app.js:46935 Uncaught Error: No uploadId found. You must initialize file-upload-with-preview with a unique uploadId.
    at new Q (app.js:46935)
    at VueComponent.saveBook (app.js:46744)
    at Proxy.boundFn (app.js:34294)
    at submit (app.js:46970)
    at invoker (app.js:36051)
    at HTMLFormElement.fn._withTask.fn._withTask (app.js:35886)

Please, how can I resolve it, or is there something I'm missing?

Thanks

**Comment by johndatserakis** [comment]
Hmm, let us look into this.

**Comment by johndatserakis** [comment]
Hey we just took a look at this - two things:

1. You don't need to `getElementById` and initialize that `p` variable. Just pass the string that you set to `data-upload-id`, like this: `let upload = new FileUploadWithPreview('myPdf')`.

2. Make sure you're not falling into the trap where the div doesn't exist yet when you're trying to call it because vue isn't finished setting up yet. For example, using `mounted` to do initialization works perfectly in our test project:

```html

<template>
  <div class="hello">

    <div class="wrapper">

      <div class="custom-file-container" data-upload-id="myFirstImage">
          <label>Upload File <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">x</a></label>
          <label class="custom-file-container__custom-file" >
              <input type="file" class="custom-file-container__custom-file__custom-file-input" accept="*" multiple>
              <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />
              <span class="custom-file-container__custom-file__custom-file-control"></span>
          </label>
          <div class="custom-file-container__image-preview"></div>
      </div>

      <button @click="check">check</button>

    </div>

  </div>
</template>

<script>
    import FileUploadWithPreview from 'file-upload-with-preview'
    export default {
        name: 'test',
        data () {
            return {
                upload: null
            }
        },
        methods: {
            check () {
                console.log(this.upload.cachedFileArray[0])
            }
        },
        mounted () {
            this.upload = new FileUploadWithPreview('myFirstImage')
        }
    }
</script>

```

Try that out.

**Comment by johndatserakis** [comment]
Did you get it going?

**Comment by cjustinobi** [comment]
Working now. Thanks

I guess it was because I was using on created() section
