### ISSUE TITLE
Multiple file input. Images still in $_FILES after deleting.

### ISSUE THREAD

**Issue by wwwAdik** [promosis/file-upload-with-preview#32]
I have found bug probably.
Case 1:
 - add 3 files one by one  in multiple file input
 - delete 2 of them
 - save form
 - expected results:  1 record in database. Test passed

Case 2:
 - add 3 files at the same time (using crtrl/cmnd button) in multiple file input
 - delete 2 of them
 - save form
 - expected results: 1 record in database. Actual: 3 records. Test FAILED

Case 3:
 - add 3 files at the same time (using crtrl/cmnd button) in multiple file input
 - delete all of them
 - save form
 - expected results: 0 records in database. Test PASSED.

Something is wrong here. Please let me know it is an issue and solve it or close this ticket if it is not

**Comment by winnery1937** [comment]
i got the same issue :/.
did you find any solution ?

**Comment by besniksh95** [comment]
+1

**Comment by winnery1937** [comment]
> +1

solved!!
the problem was on the link to the js file, was an old file.
in the new version maxfilecount is working

**Comment by johndatserakis** [comment]
Thank you @winnery1937  - perhaps @wwwAdik had been using an older version. @wwwAdik - can you confirm that updating the library fixes the issue? Thank you.

**Comment by johndatserakis** [comment]
Closing for now, thanks.
