### ISSUE TITLE
Node js environment "Element is not defined"

### ISSUE THREAD

**Issue by temiwale88** [promosis/file-upload-with-preview#33]
Hello team -

Thanks for your work! I'm trying to use this in a Node environment. But get the error:
"myDirectory\node_modules\file-upload-with-preview\dist\file-upload-with-preview.umd.js:807
        if (!Element.prototype.matches) {
        ^
ReferenceError: Element is not defined "

Here's my HTML.
`<html>
    <head>
        ...
        <link rel="stylesheet" type="text/css" href="https://unpkg.com/file-upload-with-preview@4.0.2/dist/file-upload-with-preview.min.css">
 
        
        
        ...
    </head>
    <body>
 
        ...
 
        <div class="custom-file-container" data-upload-id="myUniqueUploadId">
            <label>Upload File <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">&times;</a></label>
 
            <label class="custom-file-container__custom-file" >
                <input type="file" class="custom-file-container__custom-file__custom-file-input" accept="*" multiple aria-label="Choose File">
                <input type="hidden" name="MAX_FILE_SIZE" value="10485760" />
                <span class="custom-file-container__custom-file__custom-file-control"></span>
            </label>
            <div class="custom-file-container__image-preview"></div>
        </div>
 
        ...
 
        <script src="https://unpkg.com/file-upload-with-preview@4.0.2/dist/file-upload-with-preview.min.js"></script> 
 
        <script>
            var upload = new FileUploadWithPreview('myUniqueUploadId', {
                showDeleteButtonOnImages: true,
                text: {
                    chooseFile: 'Custom Placeholder Copy',
                    browse: 'Custom Button Copy',
                    selectedCount: 'Custom Files Selected Copy',
                },
                images: {
                    baseImage: importedBaseImage,
                },
                presetFiles: [
                    '../public/logo-promosis.png',
                    'https://images.unsplash.com/photo-1557090495-fc9312e77b28?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
                ],
            })
        </script> 
 
    </body>
</html>`

Thanks for helping me solve this!
Elijah

**Comment by johndatserakis** [comment]
Hey there, hmm yea that error kinda makes sense as this component is made to be used in a browser environment. 

I don't personally use `ssr` tech so I'm not too familiar with libraries like `Next.js` and other `ssr` libraries you may be using, but I do know that a lot of times they offer some way to mount a component in a special way as to work in that environment.

I searched the error and came across [this thread](https://stackoverflow.com/questions/39357535/referenceerror-element-is-not-defined-when-running-mocha-tests-on-reactonsen/39357780), which seems similar to your issue - I'd check out the solution in that thread as a start.

**Comment by temiwale88** [comment]
Noted. Thanks John! I saw that thread too. I think FilePond works in the Node environment and should work for me. Gracias for open sourcing your hard work!

**Comment by johndatserakis** [comment]
Thank you, appreciate it!
