### ISSUE TITLE
Image Preview DIV position

### ISSUE THREAD

**Issue by ghost** [promosis/file-upload-with-preview#35]
Is there any way to place the image preview DIV somewhere else on the page - as opposed to directly underneath the input box?

I would like the image preview to appear to the right of the input box, but when I try to move the DIV, an error is generated.

I can only assume this is due to the fact that the code expects to find the preview DIV being held within the larger custom-file-container DIV.

**Comment by johndatserakis** [comment]
I'm sorry, but in the current setup this is not possible sorry. Perhaps forking it and moving around the css and components would help.
