### ISSUE TITLE
Default Preview Image

### ISSUE THREAD

**Issue by ghost** [promosis/file-upload-with-preview#36]
I have setup a custom default preview image using the method you posted about here: https://github.com/promosis/file-upload-with-preview/issues/5

I have managed to set that up with no issue. 
The problem comes in when a user clicks the "X" to remove the image (either before or after an image has been selected) - the preview image defaults back to the original image and not the one I setup as the image to use.

I am assuming I should perhaps replace the default image value in the .js file, but not entirely sure how to do that.

**Comment by soncapham** [comment]
u must use `presetFiles: ['/folder/yourimage_here']`

**Comment by johndatserakis** [comment]
Sorry for the late response, I do not see this issue on the current demo site. If the issue still exists, please feel free to reopen.
