### ISSUE TITLE
Multiple image

### ISSUE THREAD

**Issue by GPNandhini** [promosis/file-upload-with-preview#4]
when uploaded multiple files it will overlap first one only.  not able to see multiple image

**Comment by johndatserakis** [comment]
Hey there - 

This library supports the selection of multiple files - you just have to make sure to add the `multiple` parameter to your input like so: `<input type="file" class="custom-file-container__custom-file__custom-file-input" accept="*" multiple>`. You can see this on the [demo page](https://promosis.github.io/file-upload-with-preview/) - one of the inputs only allows a single file - the other allows multiple files.

If multiple files are selected, it won't show each one in the preview box, but it will show a special display image that indicates to the user that multiple files were chosen.

Let me know if that helps!

**Comment by deniseileen** [comment]
Hi @GPNandhini, did that work for you?

**Comment by GPNandhini** [comment]
@johndatserakis  Thank you..

Hi @DeniseWalter,

No, After that i am not tried this one.

**Comment by johndatserakis** [comment]
Closing for now, let us know if you run into other issues.
