### ISSUE TITLE
Error: Could not find a 'custom-file-container' with the id of: myFirstImage

### ISSUE THREAD

**Issue by saadabdurrazaq** [promosis/file-upload-with-preview#41]
Error: Could not find a 'custom-file-container' with the id of: myFirstImage when using Vue 3

**Comment by johndatserakis** [comment]
Hmm weird, sorry I haven't really used Vue 3 yet. By the sound of the error, it seems like your Vue script is executing before the target DOM has loaded. If you can provide a codepen or jsfiddle of the issue I could take a look.

**Comment by johndatserakis** [comment]
Closing, will reopen if needed.
