### ISSUE TITLE
CORS error when get data from awss3

### ISSUE THREAD

**Issue by Adityapras** [promosis/file-upload-with-preview#43]
please help , any error when i using function 'addImagesFromPath' for display image preview 
![image](https://user-images.githubusercontent.com/20386084/136516208-35c19d43-50d1-475a-bd0a-08397ca3f8c0.png)

**Comment by johndatserakis** [comment]
Hi there. Hmm yea I think in this case you're going to have to check your settings on the AWS side and make sure you've added the proper CORS configuration on your files. I would start by taking a look at this [page](https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html).

Also - it looks like [this](https://stackoverflow.com/a/64586341) stackoverflow answer may help you out here.

**Comment by johndatserakis** [comment]
Closing, will reopen if needed.
