### ISSUE TITLE
Clear button is not working

### ISSUE THREAD

**Issue by hosseinitabar** [promosis/file-upload-with-preview#46]
Hello

I'm using your library. `fileUploadWithPreview:imagesAdded` works. `fileUploadWithPreview:imageDeleted` works. 

But `fileUploadWithPreview:clearButtonClicked` is not getting fired. 

I use `custom-file-container__image-clear` as the class of the clear button. I have not change any HTML structure.

What should I do?

**Comment by johndatserakis** [comment]
Hey there. Seems to be working for me in this [codesandbox](https://codesandbox.io/s/file-upload-with-preview-4-2-0-forked-6r3k7?file=/src/index.js). When I click the "x" above the input, I get this event triggered. Maybe take a look at this example as see if you've shifted some HTML accidentally. 

Also, please make sure you're using the latest version, `v4.2.0`, as `fileUploadWithPreview:clearButtonClicked` is a newer event.
