### ISSUE TITLE
presetFiles doesn't work with base64 encoded binary image string

### ISSUE THREAD

**Issue by ghost** [promosis/file-upload-with-preview#49]
Hi,

I'm not sure if the option "presetFiles" only works with URL. But it didn't work when I tried to use data:image. 

This function provides a convenient way of serving images from your app that are not web-accessible (e.g., in public/).

Cheers

**Comment by johndatserakis** [comment]
Hey there,

Hmm, unfortunately yes I don't think `presetFiles` will work with the string representation of an image. But I do believe it'll work with local file path. Is loading a local file into `presetFiles` by using its path not working for you?

**Comment by ghost** [comment]
Hi. 

I can preview ONE file. It works. However, I cannot preview more than one. See below.

	//  Wait for the page to be fully loaded
	window.addEventListener('load', function () {

	// Grab the data attribute data
	var additionalImg = document.querySelector('#additional_img');

	let tmpImg = additionalImg.dataset.addtimg;
	// Check if there is any image in DB, if not, intialize the library with default options
	if (tmpImg) {
	  // Initialise the library
	// Initialise the library
	var upload = new FileUploadWithPreview('addtImageUploadId', {
		//Populate the form with the data attribute
		presetFiles: additionalImg.dataset.addtimg.split(',')
	})

		// This is how we tell the to delete the current images.
	  let clearButton = document.getElementById('addtclearButton')
	  clearButton.addEventListener('click', function() {
		  document.getElementById("addtclearbox").value = 1;
	  })

	}
	else {
		// Initialise the library
	   var upload = new FileUploadWithPreview('addtImageUploadId', {})
	}
	})


HTML/PHP

    <div class="row mb-3">
		<label for="file" class="col-sm-2 form-label"><?= lang('Backend.additional_image') ?></label>
		<div class="col-sm-10" id="additional_img" data-addtimg="<?= $data_additional_img ?? null ?>">
			<div class="custom-file-container" data-upload-id="addtImageUploadId">
				<label><a href="javascript:void(0)" class="custom-file-container__image-clear" id="addtclearButton" title="<?= lang('clear_image') ?>"><?= icon('trash', '16', 'text-danger') ?></a></label>
				<label class="custom-file-container__custom-file" >
					<input type="file" name="addtimgcategory[]" id="addtimgcategory" class="custom-file-container__custom-file__custom-file-input" accept=".jpg, .jpeg, .png, .gif" aria-label="<?= lang('choose_file') ?>">
					<input type="hidden" name="addtclearbox" id="addtclearbox" value="0">
					<span class="custom-file-container__custom-file__custom-file-control"></span>
				</label>
				<div class="custom-file-container__image-preview"></div>
			</div>
		</div>
	</div>

Here is where I feed the images:

    data-addtimg="<?= $data_additional_img ?? null ?>">

I get the images from my DB as an array. So, as I said, I can preview one image, but cannot preview more than one. 

Any idea?

**Comment by johndatserakis** [comment]
Sorry it's a bit hard to read your code as the formatting seems to have gotten tripped up. But I will say that I think you may need to add the `multiple` property to the `<input type="file"` element. You can see I have it [added to the demo](https://github.com/johndatserakis/file-upload-with-preview/blob/develop/example/index.html#L47) that shows the multiple preview option, [demo here](https://johndatserakis.github.io/file-upload-with-preview/).

**Comment by ghost** [comment]
Spot on! Thank you very much!
