### ISSUE TITLE
file-upload-with-preview & Compressor.js

### ISSUE THREAD

**Issue by emresaracoglu** [promosis/file-upload-with-preview#50]
Hello,

Is there a way to use "file-upload-with-preview" and [Compressor.js](https://fengyuanchen.github.io/compressorjs/) together?

Thank you

**Comment by johndatserakis** [comment]
Hi there, I've never used that library, but I assume you'd be able to loop over the `cachedFileArray` array from your `file-upload-with-preview` initialization and apply the compression to each file as needed, before you do your actual upload.

Kinda something like this [example here](https://github.com/fengyuanchen/compressorjs/issues/46#issuecomment-401292213). You'll just have to figure out the promise situation. But yea, it seems possible.

**Comment by johndatserakis** [comment]
Closing - let me know if I can help further.

**Comment by emresaracoglu** [comment]
Hello @johndatserakis ,

I just saw your reply and am sorry for the delay. I will try your suggestion and hopefully, I can get it working successfully. Thank you for your interest.
