### ISSUE TITLE
How to access already added images while editing a form?

### ISSUE THREAD

**Issue by ghost** [promosis/file-upload-with-preview#51]
I am unable to get a preview of already added images while editing my form and when I add new images in edit form it replaces the existing ones

**Comment by johndatserakis** [comment]
It sounds like you'll need to save the existing state of your `file-upload-with-preview` before letting the user edit it.

I'm sorry I'm not sure exactly what you mean by your message. 

Although, you may need to add the `multiple` property to the `<input type="file"` element. You can see I have it [added to the demo](https://github.com/johndatserakis/file-upload-with-preview/blob/develop/example/index.html#L47) that shows the multiple preview option, [demo here](https://johndatserakis.github.io/file-upload-with-preview/).

**Comment by johndatserakis** [comment]
Closing for now. The library has recently been updated, so perhaps you can take another look and see if the add typing helps your issue.
