### ISSUE TITLE
FileUploadWithPreview is not a constructor (extended with examples)

### ISSUE THREAD

**Issue by new-user-name** [promosis/file-upload-with-preview#57]
My project structure (as simple as it gets, from Webpack manual)
[
![image](https://user-images.githubusercontent.com/70009383/165773375-01d5ec5e-96ae-45f0-8145-214abb0a1708.png)
](url)

The fileupload.js contents:
```
import {FileUploadWithPreview} from "file-upload-with-preview";
const hippo = new FileUploadWithPreview("myFirstImage");
```

The index.html:
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Getting Started</title>
</head>
<body>
<div class="custom-file-container" data-upload-id="myFirstImage"></div>
<script src="fileupload.js"></script>
</body>
</html>
```
Package.json:
```
"devDependencies": {
    "file-upload-with-preview": "^5.0.6",
    "webpack": "^5.72.0",
    "webpack-cli": "^4.9.2"
  },
```

And the result is
Uncaught TypeError: file_upload_with_preview__WEBPACK_IMPORTED_MODULE_0__.FileUploadWithPreview is not a constructor

PhpStorm syntax highlighting works fine. Import in head works fine, but I'd like to push it this way. It stems from my Laravel experience. I isolated the case from Laravel Mix down to the simplest example.

**Comment by new-user-name** [comment]
It seems that import string has to be

```import {FileUploadWithPreview} from "file-upload-with-preview.esm";```

**Comment by johndatserakis** [comment]
I see - thank you for the follow-up answer.

Yea that seems a touch strange, although I've come across projects where some that type of import is needed. I forget what it signifies exactly, but bottom line it seems like your setup wasn't able to find the correct file to auto import from. 

That information is listed in the `package.json` `module` property [here](https://github.com/johndatserakis/file-upload-with-preview/blob/develop/package.json#L48). From my research, I believe I have this setup correctly. But yea it's strange it didn't work in your case.

Glad you got it working. If you push up a test repo with just that minimal example, I'd be glad to take a look.

Thank you.
