### ISSUE TITLE
Beginner overloaded

### ISSUE THREAD

**Issue by bforpc** [promosis/file-upload-with-preview#64]
Please can you create an easy and simple example to run the upload and then use the uploaded file for beginner with nothing more than a webserver, jquery und nothing more (at this step). I dont have npm (and wont use it), because its over-overloaded for a simple upload at my own server for me only.  Thanks  _Bfo_

**Comment by johndatserakis** [comment]
Hey there - I'm super swamped at the moment so I can't make an example with an actual server. 

I have a simple non-npm example shown in this [sandbox](https://codesandbox.io/s/file-upload-with-preview-browser-446nc8?file=/src/index.js). That is the UI part of what you're looking for.

The backend part is specific to your usage - this component simply gives your users a way to upload a picture on the frontend with a preview - you'll need a backend to actually save the result to a database or storage store.

**Comment by bforpc** [comment]
Thank you very much ... it seem to be very easy.

Bfo
