### ISSUE TITLE
Can I use this inside react [just react] ?

### ISSUE THREAD

**Issue by faisol-zufaa** [promosis/file-upload-with-preview#65]
Can I use this inside react? 
If so how to? 
Can I change this components style?

**Comment by johndatserakis** [comment]
Yes that should work. I'm super busy right now so I can't get an example going for you. But one place it may start is storing the result of `const upload = new FileUploadWithPreview('myFirstImage');` to a variable in your React state.

**Comment by faisol-zufaa** [comment]
Thank you sir.
