### ISSUE TITLE
Use in Next js and Tailwind

### ISSUE THREAD

**Issue by DynaMurphy** [promosis/file-upload-with-preview#68]
Hi John

I've been trying to use this in Next js with Tailwind. But that doesn't accept this:
`<div class="custom-file-container" data-upload-id="myFirstImage"></div>`

I get the following error:
"Type '{ class: string; "data-upload-id": string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'class' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'. Did you mean 'className'?ts(2322)"

Do you have example code how to use this in Next js and Tailwind?

Thanks,
Murphy

**Comment by johndatserakis** [comment]
Hmm, interesting. I personally haven't used this with Next.js and tailwind - but one thing I'd try is to just change class to className:

```
<div className="custom-file-container" data-upload-id="myFirstImage"></div>
```

There may be more to do as far as getting this to work in a React environment - but this should fix that current error.

**Comment by johndatserakis** [comment]
Let me know if `className` didn't work for you. Will reopen if needed.

**Comment by erwannbst** [comment]
Here is an example :

```typescript
"use client";
import { useEffect } from "react";
import { FileUploadWithPreview } from "file-upload-with-preview";
import "file-upload-with-preview/dist/style.css";

export default function Uploader() {
  useEffect(() => {
    const upload = new FileUploadWithPreview("my-unique-id");
  }, []);

  return (
      <div className="custom-file-container" data-upload-id="my-unique-id"></div>
  );
}
```
