### ISSUE TITLE
bug on chooseFile label

### ISSUE THREAD

**Issue by joseehilton147** [promosis/file-upload-with-preview#69]
If I click on remove, the label come back to default text, not keeping the text I've chosen on options parameter. Example:

![image](https://user-images.githubusercontent.com/53986027/212383215-a55fb182-e069-4c21-af11-0e6b015199b1.png)

![image](https://user-images.githubusercontent.com/53986027/212383293-4e090c28-e4ac-4505-ba23-049ae7744a32.png)

After click on X
![image](https://user-images.githubusercontent.com/53986027/212383414-c6812b89-c364-49a3-969d-b79870339c55.png)

**Comment by johndatserakis** [comment]
Ahh good catch, sorry about that. Will be an easy fix - just super swamped at the moment. Will try to get to this in the next few days.

**Comment by johndatserakis** [comment]
Thank you for calling this out - fixed in https://github.com/johndatserakis/file-upload-with-preview/pull/70.

Use `v6.0.2` for the latest version.
