### ISSUE TITLE
Save in local storage

### ISSUE THREAD

**Issue by nicolasaramb** [promosis/file-upload-with-preview#72]
I would like to know if there is an option to save the images in localstorage and then add them to each input.

**Comment by johndatserakis** [comment]
Something like this wouldn't be handled automatically by the library, but you could achieve it by using the `options.presetFiles` option to supply images to show in the inputs on load. This should be relatively straight-forward after you store the images in localStorage yourself.

**Comment by johndatserakis** [comment]
Closing for now, let me know if of any further questions.
