### ISSUE TITLE
How to attach to previously initialized instance of FileUploadWithPreview?

### ISSUE THREAD

**Issue by bmarsh9** [promosis/file-upload-with-preview#73]
Hi there,

I'm dynamically creating instances of FileUploadWithPreview and I would like to access a previously initialized instance by the ID.

In some piece of code:

```
new FileUploadWithPreview.FileUploadWithPreview('id-1')
```

Access by ID in a later piece of code:

```
FileUploadWithPreview.FileUploadWithPreview('id-1').cachedFileArray
```

However this only creates a new instance of the FileUpload.. whereas I just want to attach to the old one by ID

Thank you for any help!

**Comment by johndatserakis** [comment]
Hello,

When you initialize a new file-upload-with-preview instance, you should store it in a variable.

```tsx
const upload = new FileUploadWithPreview.FileUploadWithPreview('id-1')
```

Later, you can access the latest cachedFileArray directly off your variable.

```tsx
upload.cachedFileArray
```

If you need to store multiple values, you can instantiate multiple variables, either independently or in an object.

**Comment by bmarsh9** [comment]
Thanks @johndatserakis. However in my case, I’m unable to access the variable assigned. 

For example, I may initialize FileUploadWithPreview in one function and then in some other piece of code, I need to access the uploaded files and ideally would like to just get the instance by calling the ID

**Comment by johndatserakis** [comment]
Got it. In that case, you'll need to store the variable in a place that is accessible to the other function, or, pass the variable into the function itself.

If I were doing this in React, let's say, I'd declare the variable at the top of the "waterfall", and pass down the instantiated variable as a prop to my child components. Then, the child components can use it directly.

If you're not using React, there are many other ways to make a variable "global" to the rest of the application, some safer than others. A rudimentary option for instance, if you are out of other avenues, would be to instantiate the variable and then attach it to the window object. That would make it available anywhere else in the app on that page load. 

```tsx
// Some place at the start of your app
const upload = new FileUploadWithPreview.FileUploadWithPreview('id-1')
window.upload = upload

// Elsewhere in your app...
window.upload.cachedFileArray
```

There are cleaner ways to do this, though, like using a singleton pattern. There are examples of this online.

**Comment by bmarsh9** [comment]
Thanks for the detail. I think I’ll end up refactoring a bit on my side. Ok to close
