### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by gheorghemolnar** [promosis/file-upload-with-preview#76]
Hi John,

First of all thank you for this great repo, the code is great, i had a lot of fun time studying it !
Currently, I have to support Edge / IE11 compatible mode and it's not obvious at all. 
Can you provide some insights please ?
(I'm trying to use babel, as a need to use it in a classic website: HTML + JS + CSS)

Thank you !

**Comment by johndatserakis** [comment]
Hey there - sure your best bet would be to study [this CodeSandbox](https://codesandbox.io/s/file-upload-with-preview-browser-446nc8?file=/src/index.js) - it has `file-upload-with-preview` all set up using only HTML, JS, and CSS.

Let me know of any further questions, thank you.

**Comment by gheorghemolnar** [comment]
Thanks for your update John, unfortunately the script [tag included](https://unpkg.com/file-upload-with-preview/dist/file-upload-with-preview.iife.js), has not been compiled to be compatible with IE11.
It has modern syntax, like string interpolation ...

**Comment by johndatserakis** [comment]
Sure, concerning the polyfill's specifically you can import some in the `<head>` of your HTML. I'm not sure exactly what is needed, but if you poke around at the errors you get you'll get an idea.

- Babel:
  - `<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>`
- ES6 Promises
  - `<script src="https://cdn.jsdelivr.net/es6-promise/latest/es6-promise.auto.min.js"></script>` 
- Object.assign
  - `<script src="https://cdn.jsdelivr.net/npm/es6-object-assign@1.1.0/index.min.js"></script>`
- ...etc.
