### ISSUE TITLE
How to Change Input file label? 

### ISSUE THREAD

**Issue by md-asifiqbal** [promosis/file-upload-with-preview#77]
Input file label by default set as 'Upload'. How to change this file.

<label
        >Upload File
        <a
            href="javascript:void(0)"
            class="custom-file-container__image-clear"
            title="Clear Image"
            >&times;</a
        ></label
    > 
is not working

**Comment by johndatserakis** [comment]
Sure here you go:

```ts
import { FileUploadWithPreview } from "file-upload-with-preview";
import "file-upload-with-preview/dist/style.css";

const firstUpload = new FileUploadWithPreview("myFirstImage", {
  text: { label: "New Upload Label Here" },
});
```

Further info in the docs [here](https://johndatserakis.github.io/file-upload-with-preview/typedoc/interfaces/Text.html).
