### ISSUE TITLE
Does it work with native input tag ?

### ISSUE THREAD

**Issue by bacloud22** [promosis/file-upload-with-preview#81]
Hi,
I want to set the minimal working case if possible, in other terms leave my `input type="file"` alone. I have read how one must construct the *Axios* post request with *form data* first. This seems too much for me as I started with the following and still having a lot of troubles:

```js
export const setupFileUploadWithPreview = () => {
    const formName = "addMarket"
    const form = document.querySelector(`form[name="${formName}"]`)
    const inputFile = document.getElementById("input[type='file']");
    if (!form) return;

    form.addEventListener("submit", (event) => {
        event.preventDefault();
        const formData = new FormData()
        Object.keys(form).forEach((key) => {
            formData.append(key, form[key])
        })

        axios.post('/listing', formData, {
            headers: {
                'Content-Type': 'multipart/form-data'
            },
            validateStatus: (status) => status === 599
        }).then(function (response) {
            if (response.request.responseURL !== document.URL || response.status !== 200)
                window.location.replace(response.request.responseURL)
        }).catch((error) => ("Something went wrong!", error));
    });

    const input = document.querySelector(".custom-file-container")
    if (input) {
        const upload = new FileUploadWithPreview('my-unique-id');
    }

    console.log('### function "setupFileUploadWithPreview" run successfully')
}
``` 

This is why I'm asking if there is a way to just have the nice UI component, but put the ID not on a *div* but my *input* directly 

Otherwise I find no option to go back for something like: https://stackoverflow.com/a/4459419

Thank you a lot for this library.

**Comment by johndatserakis** [comment]
Thanks for the message.

To directly answer your question, no, altering the initialization process of `file-upload-with-preview` is not possible.

Although, the initialization process I mention in the docs is simple enough, and in a lot of ways, makes the image handling process easier.

Put this in the HTML:

```html
<div class="custom-file-container" data-upload-id="my-unique-id"></div>
```

Initialize like this:

```ts
const upload = new FileUploadWithPreview('my-unique-id');
```

And then access the `upload.cachedFileArray` whenever you'd like to access the files the user has uploaded. If that's too tough in your setup, then yea it's probably best to go another route.

**Comment by johndatserakis** [comment]
Closing for now.
